#!/usr/bin/env bash
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5



for (( i = 0; i <= 100; i++))
	do
if ((i % 15 == 0))
	then
	echo "fizzbuzz"
elif ((i % 5 == 0))
	then
	echo "Buzz"
elif (( i % 3 == 0))
	then
	echo "Fizz"
	else
	echo "$i"
	fi
	done
